/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { IERC20Contract } from "./IERC20";
import { IExchangeAdapterContract } from "./IExchangeAdapter";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2MigratorContract } from "./IUniswapV2Migrator";
import { IUniswapV2PairContract } from "./IUniswapV2Pair";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { IWETHContract } from "./IWETH";
import { KittenSwapRouterContract } from "./KittenSwapRouter";
import { MigrationsContract } from "./Migrations";
import { UniswapExchangeAdapterContract } from "./UniswapExchangeAdapter";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "IERC20"): IERC20Contract;
      require(name: "IExchangeAdapter"): IExchangeAdapterContract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Migrator"): IUniswapV2MigratorContract;
      require(name: "IUniswapV2Pair"): IUniswapV2PairContract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "IWETH"): IWETHContract;
      require(name: "KittenSwapRouter"): KittenSwapRouterContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "UniswapExchangeAdapter"): UniswapExchangeAdapterContract;
    }
  }
}

export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IExchangeAdapterContract,
  IExchangeAdapterInstance,
} from "./IExchangeAdapter";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance,
} from "./IUniswapV2Factory";
export {
  IUniswapV2MigratorContract,
  IUniswapV2MigratorInstance,
} from "./IUniswapV2Migrator";
export {
  IUniswapV2PairContract,
  IUniswapV2PairInstance,
} from "./IUniswapV2Pair";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance,
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance,
} from "./IUniswapV2Router02";
export { IWETHContract, IWETHInstance } from "./IWETH";
export {
  KittenSwapRouterContract,
  KittenSwapRouterInstance,
} from "./KittenSwapRouter";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  UniswapExchangeAdapterContract,
  UniswapExchangeAdapterInstance,
} from "./UniswapExchangeAdapter";
