/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IUniswapV2MigratorContract
  extends Truffle.Contract<IUniswapV2MigratorInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IUniswapV2MigratorInstance>;
}

type AllEvents = never;

export interface IUniswapV2MigratorInstance extends Truffle.ContractInstance {
  migrate: {
    (
      token: string,
      amountTokenMin: number | BN | string,
      amountETHMin: number | BN | string,
      to: string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      token: string,
      amountTokenMin: number | BN | string,
      amountETHMin: number | BN | string,
      to: string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      token: string,
      amountTokenMin: number | BN | string,
      amountETHMin: number | BN | string,
      to: string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      token: string,
      amountTokenMin: number | BN | string,
      amountETHMin: number | BN | string,
      to: string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    migrate: {
      (
        token: string,
        amountTokenMin: number | BN | string,
        amountETHMin: number | BN | string,
        to: string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        token: string,
        amountTokenMin: number | BN | string,
        amountETHMin: number | BN | string,
        to: string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        token: string,
        amountTokenMin: number | BN | string,
        amountETHMin: number | BN | string,
        to: string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        token: string,
        amountTokenMin: number | BN | string,
        amountETHMin: number | BN | string,
        to: string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
